### ISSUE TITLE
trying to run on console

### ISSUE THREAD

**Issue by henry-hz** [spawnproc/bpe#4]
I started with erl -pa ebin, after rebar compile, and
also configured the .src file as below, but when kvs:config(dba), but I receive: [] , empty, so kvs:join(). returns me a bad argument in line 28 on kvs.erl file.

{application, kvs,
   [{description, "KVS Abstract Term Database"},
      {vsn, "1"},
      {registered, []},
      {applications, [kernel,stdlib,mnesia]},
      {mod, { kvs_app, []}},
      {dba, store_mnesia},
      {env, []} ]}.

**Comment by 5HT** [comment]
not sure you are right using app environment.
try read erlang manuals or set it manually `application:set_env(kvs,dba,store_mnesia)`.
there are also a lot of other settings you need to set up. Better see n2o or kvs samples.
